version: 2
jobs:
  build:
      docker:
        - image: phusion/baseimage:0.10.2
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Install Docker Compose
            command: |
              curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
              chmod +x ~/docker-compose
              mv ~/docker-compose /usr/local/bin/docker-compose
        - run:
            name: docker-compose build
            command: |
              cd test/integration
              docker-compose build
        - run:
            name: docker-compose up
            command: |
              cd test/integration
              docker-compose up --security-opt seccomp=unconfined --exit-code-from lightning
