version: 2
jobs:
  build:
      docker:
        - image: phusion/baseimage:0.10.2
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Install Docker Compose
            command: |
              curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
              chmod +x ~/docker-compose
              mv ~/docker-compose /usr/local/bin/docker-compose
        # - run:
        #     name: update apt-get
        #     command: |
        #       apt-get update
        #       apt-get dist-upgrade -y
        #       apt-get install -y git curl
        - run:
            name: clone regtest & pull rust nightly
            command: |
              cd test/integration
              # docker-compose up
              # docker-compose exec regtest-0 /bin/sh -c "ls -l && pwd && cat /bitcoin/0.conf"
              docker-compose up --exit-code-from lightning
              # docker-compose up --abort-on-container-exit
